node-sportify:
  extends:
    file: common.yml
    service: node-sportify
  #command: npm start
  environment:
    - NODE_ENV=development
  links:
    - sportify
  volumes:
    - ~/Code/node-sportify:/usr/src/app

sportify:
  extends:
    file: common.yml
    service: sportify
  volumes:
    - ~/Code/sportify:/app
    - ~/.ivy2:/root/.ivy2
