sportify_app:
  extends:
    file: common.yml
    service: sportify_app
  environment:
    - NODE_ENV=development
    - VIRTUAL_HOST=node.sportify.local
    - VIRTUAL_PORT=3000
  links:
    - sportify

sportify:
  extends:
    file: common.yml
    service: sportify
  environment:
    - VIRTUAL_HOST=play.sportify.local
    - VIRTUAL_PORT=9000
  volumes:
    - ~/.ivy2:/root/.ivy2
  
nginx:
  container_name: nginx-proxy
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"
