node-sportify:
 extends:
   file: common.yml
   service: node-sportify
 command: nodemon -L bin/www & gulp
 environment:
   - NODE_ENV=development
 links:
   - sportify
 #ports:
 #  - "35729:35729" # livereload
 # restart: always
 volumes:
   - ~/Code/node-sportify:/usr/src/app

sportify:
  extends:
    file: common.yml
    service: sportify
  command: activator -Dconfig.file=/app/conf/development.conf run
  environment:
    - SPORTIFY_DB_NAME_DEV
    - SPORTIFY_MONGO_URL_DEV
  links:
    - mongo
  #restart: always
  stdin_open: true # https://github.com/playframework/playframework/issues/4001
  volumes:
    - ~/Code/sportify:/app
    - ~/.ivy2:/root/.ivy2

data:
  command: echo mongo data volume created successfully
  image: mongo:3.0.6
  container_name: mongodata
  volumes:
    - /data/db

mongo:
  image: mongo:3.0.6
  container_name: mongo
  command: "--smallfiles"
  mem_limit: 100MB
  ports:
    - "27017:27017"
  #restart: always
  volumes_from:
    - data
