node-sportify:
  extends:
    file: common.yml
    service: node-sportify
  command: gulp
  environment:
    - NODE_ENV=development
  links:
    - sportify
  ports:
    - "35729:35729" # livereload
  volumes:
    - ~/Code/node-sportify:/usr/src/app

sportify:
  extends:
    file: common.yml
    service: sportify
  volumes:
    - ~/Code/sportify:/app
    - ~/.ivy2:/root/.ivy2
