node-sportify:
  extends:
    file: common.yml
    service: node-sportify
  command: npm run start # this should probably use forever to ensure it keeps running
  environment:
    - NODE_ENV=production
  links:
    - sportify
  restart: always

sportify:
  extends:
    file: common.yml
    service: sportify
  command: activator -mem 512 start
  restart: always
