node-sportify:
  extends:
    file: common.yml
    service: node-sportify
  command: node ./bin/www # this should probably use forever to ensure it keeps running
  environment:
    - NODE_ENV=production
  links:
    - sportify

sportify:
  extends:
    file: common.yml
    service: sportify
