sportify_app:
  extends:
    file: common.yml
    service: sportify_app
  environment:
    - NODE_ENV=production
  links:
    - sportify

sportify:
  extends:
    file: common.yml
    service: sportify
