node-sportify:
  extends:
    file: common.yml
    service: node-sportify
  command: node ./bin/www
  environment:
    - NODE_ENV=production
  links:
    - sportify

sportify:
  extends:
    file: common.yml
    service: sportify
